import {
  University,
  Faculty,
  Department,
  Course,
  LectureNote,
  Professor,
  LeaderboardEntry,
  UserProfile,
  PricingTier,
  TierInfo,
  NoteEarning,
  PresentationTemplate,
  ModerationItem,
  AdminUserRecord,
  VerificationRequest,
  CopyrightClaim,
  PayoutRequest,
  TierUploadStat,
  DailyActiveStat,
  RevenueStat,
  AdminNotification,
  AdminOverviewStats
} from './types';

export const MOCK_TIERS: TierInfo[] = [
  {
    id: 'ilkokul',
    name: 'İlkokul (1 - 4. Sınıf)',
    shortName: 'İlkokul',
    iconName: 'Smile',
    badgeColor: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300 border-emerald-500/30',
    description: 'Okuma-yazma çalışmaları, 1-4. sınıf Matematik, Türkçe ve Hayat Bilgisi özetleri.'
  },
  {
    id: 'ortaokul',
    name: 'Ortaokul & LGS (5 - 8. Sınıf)',
    shortName: 'Ortaokul',
    iconName: 'BookOpen',
    badgeColor: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-300 border-cyan-500/30',
    description: '5-8. Sınıf ders notları, Fen Bilimleri, Sosyal Bilgiler ve LGS çıkmış denemeler.'
  },
  {
    id: 'lise',
    name: 'Lise & YKS (TYT / AYT)',
    shortName: 'Lise & YKS',
    iconName: 'GraduationCap',
    badgeColor: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-300 border-indigo-500/30',
    description: '9-12. Sınıf Fizik, Kimya, Biyoloji, Matematik özetleri ve TYT/AYT YKS derece notları.'
  },
  {
    id: 'lisans',
    name: 'Üniversite (Lisans)',
    shortName: 'Üniversite',
    iconName: 'Cpu',
    badgeColor: 'bg-blue-500/10 text-blue-600 dark:text-blue-300 border-blue-500/30',
    description: 'Mühendislik, Tıp, Hukuk, İİBF vize/final çıkmış soruları ve ders slayt özetleri.'
  },
  {
    id: 'akademik',
    name: 'İleri Akademik (Lisansüstü & Prof)',
    shortName: 'İleri Akademik',
    iconName: 'Microscope',
    badgeColor: 'bg-purple-500/10 text-purple-600 dark:text-purple-300 border-purple-500/30',
    description: 'Yüksek Lisans, Doktora tez özetleri, Doçentlik sözlü sınav sunumları ve makale analizleri.'
  }
];

export const MOCK_UNIVERSITIES: University[] = [
  { id: '1', name: 'İstanbul Teknik Üniversitesi', shortName: 'İTÜ', city: 'İstanbul', facultyCount: 13, noteCount: 12450, studentCount: 38000 },
  { id: '2', name: 'Orta Doğu Teknik Üniversitesi', shortName: 'ODTÜ', city: 'Ankara', facultyCount: 11, noteCount: 10890, studentCount: 32000 },
  { id: '3', name: 'Boğaziçi Üniversitesi', shortName: 'BÜ', city: 'İstanbul', facultyCount: 9, noteCount: 8940, studentCount: 19500 },
  { id: '4', name: 'Hacettepe Üniversitesi', shortName: 'HÜ', city: 'Ankara', facultyCount: 16, noteCount: 14200, studentCount: 45000 },
  { id: '5', name: 'Yıldız Teknik Üniversitesi', shortName: 'YTÜ', city: 'İstanbul', facultyCount: 10, noteCount: 7650, studentCount: 31000 }
];

export const MOCK_FACULTIES: Faculty[] = [
  {
    id: 'fac-1',
    slug: 'muhendislik',
    name: 'Mühendislik Fakültesi',
    iconName: 'Cpu',
    description: 'Yazılım, Yapay Zekâ, Makine, Elektrik-Elektronik ve İnşaat Ders Notları',
    departmentCount: 12,
    totalNotes: 18450,
    colorGradient: 'from-blue-600 via-indigo-600 to-cyan-500'
  },
  {
    id: 'fac-2',
    slug: 'tip-ve-saglik',
    name: 'Tıp ve Sağlık Bilimleri Fakültesi',
    iconName: 'Stethoscope',
    description: 'Anatomi atlasları, Histoloji slaytları, TUS çalışma özetleri ve Klinikte Vaka Notları',
    departmentCount: 6,
    totalNotes: 14200,
    colorGradient: 'from-emerald-600 via-teal-600 to-cyan-600'
  },
  {
    id: 'fac-3',
    slug: 'hukuk',
    name: 'Hukuk Fakültesi',
    iconName: 'Scale',
    description: 'Anayasa, Medeni Hukuk, Ceza Hukuku ders özetleri, Yargıtay emsal kararları',
    departmentCount: 4,
    totalNotes: 9800,
    colorGradient: 'from-amber-600 via-orange-600 to-yellow-500'
  }
];

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    slug: 'bilgisayar-muhendisligi',
    facultySlug: 'muhendislik',
    name: 'Bilgisayar Mühendisliği',
    code: 'CENG',
    description: 'Algoritmalar, Veri Yapıları, İşletim Sistemleri, Siber Güvenlik ve Yapay Zekâ.',
    activeCoursesCount: 42,
    totalNotesCount: 4850
  },
  {
    id: 'dept-4',
    slug: 'tip-doktorlugu',
    facultySlug: 'tip-ve-saglik',
    name: 'Tıp (Genel Tıp)',
    code: 'MED',
    description: 'Dönem 1 Histoloji, Dönem 2 Fizyoloji, Dönem 3 Patoloji ve Klinik Staj Notları.',
    activeCoursesCount: 28,
    totalNotesCount: 8900
  }
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'course-elem-1',
    code: 'MAT 101-İLK',
    name: '1. Sınıf İlkokuma Yazma & Temel Rakamlar',
    educationTier: 'ilkokul',
    level: '1. Sınıf',
    professors: ['Zeynep Öğretmen'],
    totalNotes: 84,
    examCount: 12,
    description: 'Çizgi çalışmaları, ses grupları (ANETİL), ritmik sayma ve el kası geliştirme fasikülleri.'
  },
  {
    id: 'course-mid-1',
    code: 'LGS MAT',
    name: '8. Sınıf LGS Yeni Nesil Matematik',
    educationTier: 'ortaokul',
    level: '8. Sınıf (LGS)',
    professors: ['Mustafa Hoca (LGS Uzmanı)'],
    totalNotes: 195,
    examCount: 42,
    description: 'Çarpanlar ve Katlar, Üslü İfadeler, Kareköklü İfadeler ve Mantık Muhakeme Soruları.'
  },
  {
    id: 'course-high-1',
    code: 'YKS FİZ',
    name: '11. Sınıf & TYT-AYT Fizik Vektörler',
    educationTier: 'lise',
    level: '11. Sınıf',
    professors: ['Kemal Yılmaz (Fizik Öğretmeni)'],
    totalNotes: 310,
    examCount: 68,
    description: 'Vektörler, Bağıl Hareket, Newton’un Hareket Yasaları ve Atışlar Formül Kitapçığı.'
  },
  {
    id: 'course-1',
    code: 'CENG 201',
    name: 'Veri Yapıları ve Algoritma Analizi',
    educationTier: 'lisans',
    departmentSlug: 'bilgisayar-muhendisligi',
    level: 'Lisans 2. Sınıf',
    credits: 4,
    professors: ['Prof. Dr. Ahmet Yılmaz', 'Doç. Dr. Ayşe Kaya'],
    totalNotes: 142,
    examCount: 28,
    description: 'İkili Arama Ağaçları, Graph Algoritmaları (Dijkstra, BFS/DFS) ve Big-O Analizi.'
  },
  {
    id: 'course-adv-1',
    code: 'AI DOKTORA',
    name: 'Derin Öğrenme ve Transformer Mimarileri',
    educationTier: 'akademik',
    level: 'Doktora',
    professors: ['Prof. Dr. Selin Korkmaz'],
    totalNotes: 78,
    examCount: 15,
    description: 'Attention Mechanisms, LLM Fine-tuning, Doçentlik Sözlü Sınav Sunumu ve Tezler.'
  }
];

export const MOCK_PROFESSORS: Professor[] = [
  {
    id: 'prof-1',
    name: 'Prof. Dr. Ahmet Yılmaz',
    title: 'Prof. Dr.',
    university: 'İstanbul Teknik Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    rating: 4.9,
    verifiedCount: 84,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80'
  },
  {
    id: 'prof-2',
    name: 'Zeynep Öğretmen',
    title: 'Uzman Öğretmen',
    university: 'Milli Eğitim Bakanlığı',
    department: 'İlköğretim',
    rating: 4.95,
    verifiedCount: 120,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80'
  }
];

export const MOCK_NOTES: LectureNote[] = [
  // 1. İLKOKUL NOTU
  {
    id: 'note-elem-101',
    title: '1. Sınıf İlkokuma Yazma Çizgi Çalışmaları & ANETİL Ses Grubu Fasikülü',
    description: 'MEB müfredatına birebir uygun. Harf hissettirme çalışmaları, dik temel harfler, eğlenceli çizgi alıştırmaları ve renkli okuma metinleri.',
    educationTier: 'ilkokul',
    courseCode: 'OKUMA 101',
    courseName: '1. Sınıf Okuma Yazma Etkinlikleri',
    level: '1. Sınıf',
    examType: 'Okul Sınavı',
    professorName: 'Zeynep Öğretmen',
    authorName: 'Elif Öğretmen',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    authorBadge: 'Öğretmen / Eğitmen',
    academicYear: '2025-2026',
    fileFormat: 'PDF',
    pageCount: 24,
    fileSizeBytes: 3200000,
    rating: 4.96,
    reviewCount: 98,
    downloadCount: 4200,
    viewCount: 15400,
    dijipuanPrice: 0,
    isVerifiedByProfessor: true,
    isAiOcrProcessed: true,
    tags: ['İlkokul 1. Sınıf', 'Okuma Yazma', 'Çizgi Çalışması', 'MEB Müfredatı'],
    previewPages: [
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80'
    ],
    ocrSummary: {
      summaryTitle: 'İlkokul 1. Sınıf Okuma AI Rehberi',
      overview: 'Bu çalışmada ilk ses grubu olan A-N-E-T-İ-L harflerinin birleştirilmesi ve hece tabloları sunulmaktadır.',
      keyPoints: [
        'A + N = AN, E + L = EL Hece Birleştirme',
        'El Kaslarını Geliştirici Noktaları Birleştirme Çizgileri',
        'Sesli ve Sessiz Harf Ayırt Etme Renklendirme Sayfaları'
      ],
      formulaeOrKeywords: ['A-N-E-T-İ-L Ses Grubu', 'Dik Temel Harfler'],
      probableExamQuestions: [
        { question: 'Verilen görsellerin altına başladığı harfi yazınız.', topic: 'Ses Bilgisi', difficulty: 'Kolay' }
      ],
      aiConfidenceScore: 99.5
    },
    comments: [],
    createdAt: '2026-02-10'
  },

  // 2. ORTAOKUL NOTU
  {
    id: 'note-mid-101',
    title: '8. Sınıf LGS Matematik Yeni Nesil Soru Bankası & Adım Adım Çözümler',
    description: 'LGS sınavında %100 çıkan Çarpanlar ve Katlar, EBOB-EKOK, Kareköklü İfadeler ve Veri Analizi yeni nesil beceri temelli soru seti.',
    educationTier: 'ortaokul',
    courseCode: 'LGS MAT',
    courseName: '8. Sınıf LGS Matematik',
    level: '8. Sınıf (LGS)',
    examType: 'LGS Denemesi',
    professorName: 'Mustafa Hoca',
    authorName: 'Caner Şahin (LGS 1.si)',
    authorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    authorBadge: 'Derece Öğrencisi',
    academicYear: '2025-2026',
    fileFormat: 'PDF',
    pageCount: 40,
    fileSizeBytes: 5800000,
    rating: 4.92,
    reviewCount: 165,
    downloadCount: 6800,
    viewCount: 24000,
    dijipuanPrice: 10,
    isVerifiedByProfessor: true,
    isAiOcrProcessed: true,
    tags: ['8. Sınıf', 'LGS Matematik', 'EBOB EKOK', 'Yeni Nesil Sorular'],
    previewPages: [
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80'
    ],
    ocrSummary: {
      summaryTitle: 'LGS Matematik AI Sınav Tüyoları',
      overview: 'LGS matematik sorularında verilen grafik ve şekil analizlerini hızlandırma yöntemleri.',
      keyPoints: [
        'EBOB Kullanım Alanları: İki kaba ayrılan sıvılar, eşit aralıklarla dikilen ağaçlar',
        'EKOK Kullanım Alanları: Birlikte çalan ziller, yan yana dizilen tuğlalar'
      ],
      formulaeOrKeywords: ['EBOB(a,b) * EKOK(a,b) = a * b'],
      probableExamQuestions: [
        { question: 'Aralarında asal iki sayının EKOK’u 120 ise toplamı en az kaçtır?', topic: 'Çarpanlar Katlar', difficulty: 'Orta' }
      ],
      aiConfidenceScore: 98.9
    },
    comments: [],
    createdAt: '2026-03-01'
  },

  // 3. LİSE NOTU
  {
    id: 'note-high-101',
    title: '11. Sınıf & TYT/AYT Fizik Vektörler & Bağıl Hareket Formül ve Soru Kılavuzu',
    description: 'YKS Fizik için derece yaptıran tam özet. İki ve üç boyutlu vektörlerde bileşke bulma, Nehirde Hareket ve Newton Yasaları pratik çözümleri.',
    educationTier: 'lise',
    courseCode: 'YKS FİZ',
    courseName: 'Fizik (Mekanik & Vektörler)',
    level: '12. Sınıf (TYT/AYT)',
    examType: 'TYT / AYT',
    professorName: 'Kemal Yılmaz',
    authorName: 'Deniz Kaya (YKS Sayısal 142.si)',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    authorBadge: 'Derece Öğrencisi',
    academicYear: '2025-2026',
    fileFormat: 'PDF',
    pageCount: 32,
    fileSizeBytes: 4900000,
    rating: 4.97,
    reviewCount: 230,
    downloadCount: 9400,
    viewCount: 31000,
    dijipuanPrice: 15,
    isVerifiedByProfessor: true,
    isAiOcrProcessed: true,
    tags: ['YKS Fizik', 'TYT AYT', '11. Sınıf Fizik', 'Vektörler'],
    previewPages: [
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80'
    ],
    ocrSummary: {
      summaryTitle: 'YKS Fizik AI OCR Özet Haritası',
      overview: 'Vektörlerin bileşenlerine ayrılması ve nehir problemlerinde akıntı hızının karşı kıyıya ulaşma süresine etkisi.',
      keyPoints: [
        'Karşı Kıyıya Ulaşma Süresi (t) = d / (Vy)',
        'Akıntı Hızı (Va) Yalnızca Sürüklenme Miktarını Değiştirir, Karşıya Geçiş Süresini Etkilemez!'
      ],
      formulaeOrKeywords: ['Vbağıl = Vgözlenen - Vgözlemci', 'Fnet = m * a'],
      probableExamQuestions: [
        { question: 'Akıntı hızı 3 m/s olan nehirde suya göre hızı 5 m/s olan yüzücünün sürüklenme mesafesi nedir?', topic: 'Bağıl Hareket', difficulty: 'Orta' }
      ],
      aiConfidenceScore: 99.1
    },
    comments: [],
    createdAt: '2026-01-15'
  },

  // 4. LİSANS NOTU
  {
    id: 'note-101',
    title: 'Veri Yapıları ve Algoritmalar - Eksiksiz Vize Özet Kitapçığı & Kod Çözümleri',
    description: 'İTÜ CENG 201 dersi için Prof. Dr. Ahmet Yılmaz müfredatına birebir uygun. AVL Trees, Red-Black Trees, Graph Traversal ve Sınav Soruları.',
    educationTier: 'lisans',
    university: 'İstanbul Teknik Üniversitesi',
    faculty: 'Mühendislik Fakültesi',
    facultySlug: 'muhendislik',
    department: 'Bilgisayar Mühendisliği',
    deptSlug: 'bilgisayar-muhendisligi',
    courseCode: 'CENG 201',
    courseName: 'Veri Yapıları ve Algoritma Analizi',
    level: 'Lisans 2. Sınıf',
    examType: 'Vize',
    professorName: 'Prof. Dr. Ahmet Yılmaz',
    authorName: 'Ege Kaan Şahin',
    authorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    authorBadge: 'Derece Öğrencisi',
    academicYear: '2025-2026 Güz',
    fileFormat: 'PDF',
    pageCount: 38,
    fileSizeBytes: 4200000,
    rating: 4.95,
    reviewCount: 142,
    downloadCount: 3820,
    viewCount: 14500,
    dijipuanPrice: 0,
    isVerifiedByProfessor: true,
    isAiOcrProcessed: true,
    tags: ['Tree Structures', 'Big-O', 'Graph Algorithms', 'Çıkmış Sorular', 'İTÜ'],
    previewPages: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80'
    ],
    ocrSummary: {
      summaryTitle: 'Yapay Zekâ OCR Not Özeti & Sınav Tüyoları',
      overview: 'Bu ders notu CENG 201 Vize sınavında %85 oranında sorulan temel ağaç ve grafik algoritmalarını açıklar.',
      keyPoints: [
        'Big-O Zaman Karmaşıklığı: O(1) < O(log N) < O(N) < O(N log N) < O(N^2)',
        'AVL Ağacı Dengeleme: Left-Left ve Right-Left Rotasyon Kuralları'
      ],
      formulaeOrKeywords: ['Height(Tree) = max(Height(Left), Height(Right)) + 1'],
      probableExamQuestions: [
        { question: 'Verilen bir AVL ağacına eleman eklendiğinde rotasyon adımlarını çizin.', topic: 'AVL Trees', difficulty: 'Zor' }
      ],
      aiConfidenceScore: 98.4
    },
    comments: [],
    createdAt: '2026-03-12'
  },

  // 5. İLERİ AKADEMİK NOTU
  {
    id: 'note-adv-101',
    title: 'Derin Öğrenme ve Transformer Mimarileri Doktora Tez Özeti & Sunumu',
    description: 'Yapay Zekâ Doktora ve Doçentlik adayları için hazırlanan Attention Mechanisms, Positional Encoding ve LLM Fine-Tuning akademik inceleme raporu.',
    educationTier: 'akademik',
    university: 'ODTÜ / Bilkent',
    faculty: 'Mühendislik Fakültesi',
    facultySlug: 'muhendislik',
    department: 'Bilgisayar Mühendisliği',
    deptSlug: 'bilgisayar-muhendisligi',
    courseCode: 'AI DOKTORA',
    courseName: 'İleri Derin Öğrenme Araştırmaları',
    level: 'Doktora',
    examType: 'Tez Özeti',
    professorName: 'Prof. Dr. Selin Korkmaz',
    authorName: 'Dr. Arda Yılmaz',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    authorBadge: 'Akademisyen',
    academicYear: '2025-2026',
    fileFormat: 'PDF',
    pageCount: 56,
    fileSizeBytes: 14200000,
    rating: 4.99,
    reviewCount: 78,
    downloadCount: 1850,
    viewCount: 7900,
    dijipuanPrice: 25,
    isVerifiedByProfessor: true,
    isAiOcrProcessed: true,
    tags: ['Doktora Tezi', 'Transformer Architecture', 'Attention Mechanism', 'Doçentlik Sunumu'],
    previewPages: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80'
    ],
    ocrSummary: {
      summaryTitle: 'Doktora AI İleri Akademik Özet',
      overview: 'Vaswani et al. "Attention Is All You Need" makalesi ve Multi-Head Self-Attention matris hesaplamaları.',
      keyPoints: [
        'Self-Attention(Q, K, V) = softmax((Q * K^T) / sqrt(dk)) * V',
        'LoRA (Low-Rank Adaptation) ile LLM İnce Ayar (Fine-Tuning) Verimliliği'
      ],
      formulaeOrKeywords: ['MultiHead(Q,K,V) = Concat(head1,...,headh) * Wo'],
      probableExamQuestions: [
        { question: 'Self-Attention karmaşıklığının O(N^2) olma sebebi ve FlashAttention çözümü nedir?', topic: 'Deep Learning', difficulty: 'Zor' }
      ],
      aiConfidenceScore: 99.7
    },
    comments: [],
    createdAt: '2026-04-05'
  }
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    id: 'user-top-1',
    name: 'Ege Kaan Şahin',
    university: 'İstanbul Teknik Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    totalUploads: 48,
    totalDownloads: 19400,
    earnedDijipuan: 4850,
    reputationScore: 998,
    badgeTitle: 'Şampiyon Not Yazarı',
    educationTier: 'lisans',
    role: 'PRO_STUDENT',
    isVerifiedEducator: false,
    rankDelta: 0,
    averageRating: 4.95,
  },
  {
    rank: 2,
    id: 'user-top-2',
    name: 'Dr. Arda Yılmaz',
    university: 'Orta Doğu Teknik Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    totalUploads: 67,
    totalDownloads: 17850,
    earnedDijipuan: 8920,
    reputationScore: 975,
    badgeTitle: 'Akademik Otorite',
    educationTier: 'akademik',
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    rankDelta: 1,
    averageRating: 4.99,
  },
  {
    rank: 3,
    id: 'user-top-3',
    name: 'Zeynep Öğretmen',
    university: 'Milli Eğitim Bakanlığı',
    department: 'İlköğretim',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    totalUploads: 120,
    totalDownloads: 16200,
    earnedDijipuan: 6120,
    reputationScore: 940,
    badgeTitle: 'Efsane Eğitmen',
    educationTier: 'ilkokul',
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    rankDelta: -1,
    averageRating: 4.96,
  },
  {
    rank: 4,
    id: 'user-top-4',
    name: 'Deniz Kaya',
    university: 'YKS Sayısal 142.si',
    department: 'Lise & YKS (TYT/AYT)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    totalUploads: 39,
    totalDownloads: 14900,
    earnedDijipuan: 3980,
    reputationScore: 912,
    badgeTitle: 'YKS Derece Rehberi',
    educationTier: 'lise',
    role: 'PRO_STUDENT',
    isVerifiedEducator: false,
    rankDelta: 3,
    averageRating: 4.97,
  },
  {
    rank: 5,
    id: 'user-top-5',
    name: 'Elif Öğretmen',
    university: 'Milli Eğitim Bakanlığı',
    department: 'İlköğretim 1. Sınıf',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    totalUploads: 58,
    totalDownloads: 13400,
    earnedDijipuan: 3400,
    reputationScore: 880,
    badgeTitle: 'Fasikül Ustası',
    educationTier: 'ilkokul',
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    rankDelta: 0,
    averageRating: 4.94,
  },
  {
    rank: 6,
    id: 'user-top-6',
    name: 'Caner Şahin',
    university: 'Özel Bahçeşehir Koleji',
    department: '8. Sınıf (LGS)',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    totalUploads: 22,
    totalDownloads: 11800,
    earnedDijipuan: 1320,
    reputationScore: 845,
    badgeTitle: 'LGS Şampiyonu',
    educationTier: 'ortaokul',
    role: 'PRO_STUDENT',
    isVerifiedEducator: false,
    rankDelta: 2,
    averageRating: 4.92,
  },
  {
    rank: 7,
    id: 'user-top-7',
    name: 'Prof. Dr. Selin Korkmaz',
    university: 'Bilkent Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    totalUploads: 31,
    totalDownloads: 9600,
    earnedDijipuan: 5240,
    reputationScore: 810,
    badgeTitle: 'Doktora Mentoru',
    educationTier: 'akademik',
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    rankDelta: -2,
    averageRating: 4.98,
  },
  {
    rank: 8,
    id: 'user-top-8',
    name: 'Selin Yıldız',
    university: 'Özel Ted Koleji',
    department: '12. Sınıf (TYT/AYT)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    totalUploads: 14,
    totalDownloads: 7300,
    earnedDijipuan: 890,
    reputationScore: 604,
    badgeTitle: 'Yükselen Yıldız',
    educationTier: 'lise',
    role: 'PRO_STUDENT',
    isVerifiedEducator: false,
    rankDelta: 5,
    averageRating: 4.88,
  },
  {
    rank: 9,
    id: 'user-top-9',
    name: 'Can Yılmaz',
    university: 'İstanbul Teknik Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    totalUploads: 14,
    totalDownloads: 5820,
    earnedDijipuan: 1450,
    reputationScore: 480,
    badgeTitle: 'Aktif Katkıcı',
    educationTier: 'lisans',
    role: 'PRO_STUDENT',
    isVerifiedEducator: false,
    rankDelta: -1,
    averageRating: 4.71,
  },
  {
    rank: 10,
    id: 'user-top-10',
    name: 'Mert Aydın',
    university: 'Yıldız Teknik Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    totalUploads: 6,
    totalDownloads: 2140,
    earnedDijipuan: 340,
    reputationScore: 285,
    badgeTitle: 'Yeni Katılan',
    educationTier: 'lisans',
    role: 'FREE_STUDENT',
    isVerifiedEducator: false,
    rankDelta: 4,
    averageRating: 4.52,
  },
  {
    rank: 11,
    id: 'user-top-11',
    name: 'Fatma Aksoy',
    university: 'Milli Eğitim Bakanlığı',
    department: 'Ortaokul Matematik',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    totalUploads: 27,
    totalDownloads: 8450,
    earnedDijipuan: 2180,
    reputationScore: 742,
    badgeTitle: 'LGS Koçu',
    educationTier: 'ortaokul',
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    rankDelta: 1,
    averageRating: 4.9,
  },
  {
    rank: 12,
    id: 'user-top-12',
    name: 'Ayşe Demir',
    university: 'Hacettepe Üniversitesi',
    department: 'Tıp (Genel Tıp)',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    totalUploads: 3,
    totalDownloads: 960,
    earnedDijipuan: 210,
    reputationScore: 120,
    badgeTitle: 'Çaylak',
    educationTier: 'lisans',
    role: 'FREE_STUDENT',
    isVerifiedEducator: false,
    rankDelta: 0,
    averageRating: 4.4,
  },
];

export const MOCK_USER: UserProfile = {
  id: 'user-current',
  name: 'Can Yılmaz',
  email: 'can.yilmaz@itu.edu.tr',
  university: 'İstanbul Teknik Üniversitesi',
  department: 'Bilgisayar Mühendisliği',
  academicLevel: 'Lisans 3. Sınıf',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  dijipuanBalance: 1450,
  reputationScore: 480,
  uploadedCount: 14,
  downloadedCount: 82,
  savedCount: 23,
  tier: 'Pro Akademik',
  role: 'PRO_STUDENT',
  monthlyDownloadsUsed: 0,
  monthlyDownloadLimit: -1,
  isVerifiedEducator: false,
  offlineSyncEnabled: true,
  totalEarningsMonthly: 0,
  totalEarningsAllTime: 0,
};

export const MOCK_USER_FREE: UserProfile = {
  id: 'user-free',
  name: 'Ayşe Demir',
  email: 'ayse.demir@ogr.hacettepe.edu.tr',
  university: 'Hacettepe Üniversitesi',
  department: 'Tıp (Genel Tıp)',
  academicLevel: 'Lisans 1. Sınıf',
  avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
  dijipuanBalance: 210,
  reputationScore: 120,
  uploadedCount: 3,
  downloadedCount: 4,
  savedCount: 8,
  tier: 'Ücretsiz',
  role: 'FREE_STUDENT',
  monthlyDownloadsUsed: 4,
  monthlyDownloadLimit: 5,
  isVerifiedEducator: false,
  offlineSyncEnabled: false,
  totalEarningsMonthly: 0,
  totalEarningsAllTime: 0,
};

export const MOCK_USER_RESEARCHER: UserProfile = {
  id: 'user-researcher',
  name: 'Dr. Arda Yılmaz',
  email: 'arda.yilmaz@odtu.edu.tr',
  university: 'Orta Doğu Teknik Üniversitesi',
  department: 'Bilgisayar Mühendisliği',
  academicLevel: 'Doktora',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
  dijipuanBalance: 8920,
  reputationScore: 975,
  uploadedCount: 67,
  downloadedCount: 340,
  savedCount: 95,
  tier: 'Araştırmacı / Doçent',
  role: 'RESEARCHER_DOCENT',
  monthlyDownloadsUsed: 0,
  monthlyDownloadLimit: -1,
  isVerifiedEducator: true,
  offlineSyncEnabled: true,
  totalEarningsMonthly: 2840,
  totalEarningsAllTime: 34600,
};

export const MOCK_NOTE_EARNINGS: NoteEarning[] = [
  {
    id: 'earn-1',
    noteTitle: 'Derin Öğrenme ve Transformer Mimarileri Doktora Tez Özeti',
    courseCode: 'AI DOKTORA',
    salesCount: 142,
    earningsTotal: 18600,
    earningsThisMonth: 1240,
    date: '2026-04-05',
    status: 'active',
  },
  {
    id: 'earn-2',
    noteTitle: 'Doçentlik Sözlü Sınav Hazırlık Sunumu & Jüri Tüyoları',
    courseCode: 'DOÇENT 001',
    salesCount: 89,
    earningsTotal: 11200,
    earningsThisMonth: 980,
    date: '2026-03-18',
    status: 'active',
  },
  {
    id: 'earn-3',
    noteTitle: 'Yapay Zekâ Etik ve Regülasyon Politika Taslakları',
    courseCode: 'AI ETİK',
    salesCount: 34,
    earningsTotal: 4800,
    earningsThisMonth: 620,
    date: '2026-05-01',
    status: 'pending',
  },
];

export const MOCK_TEMPLATES: PresentationTemplate[] = [
  {
    id: 'tmpl-1',
    title: 'Doktora Tez Savunması - Modern Akademik Şablon',
    category: 'doktora',
    slides: 42,
    downloads: 4820,
    preview: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80',
    isPremium: true,
  },
  {
    id: 'tmpl-2',
    title: 'Doçentlik Sözlü Sınav Sunumu - Minimalist',
    category: 'docentlik',
    slides: 28,
    downloads: 3100,
    preview: 'https://images.unsplash.com/photo-1558403194-611308249627?auto=format&fit=crop&w=600&q=80',
    isPremium: true,
  },
  {
    id: 'tmpl-3',
    title: 'Uluslararası Konferans Bildiri Şablonu',
    category: 'konferans',
    slides: 18,
    downloads: 7200,
    preview: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=600&q=80',
    isPremium: false,
  },
  {
    id: 'tmpl-4',
    title: 'Yüksek Lisans Tez Teslim Şablonu - APA 7',
    category: 'tez',
    slides: 0,
    downloads: 5640,
    preview: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80',
    isPremium: false,
  },
];


export const MOCK_PRICING_TIERS: PricingTier[] = [
  {
    id: 'free',
    name: 'Ücretsiz Öğrenci',
    priceMonthly: 0,
    priceYearly: 0,
    description: 'Temel düzeyde tüm halka açık ders notlarına erişim ve dijipuan kazanma başlangıcı.',
    features: [
      'Aylık 5 Adet Ücretsiz Ders Notu İndirme',
      'Halka Açık OCR Özetlerini Görüntüleme',
      'Temel Arama ve Kademe Filtreleme',
      'Not Yükleyerek Dijipuan Kazanma'
    ],
    ctaText: 'Hemen Başla'
  },
  {
    id: 'pro-academic',
    name: 'Pro Öğrenci & YKS',
    badge: 'En Popüler',
    priceMonthly: 49,
    priceYearly: 470,
    popular: true,
    description: 'LGS, YKS, Vize/Final sınav dönemlerinde derece hedefleyen öğrenciler için.',
    features: [
      'Sınırsız PDF Ders Notu & Soru Bankası İndirme',
      'Yapay Zekâ OCR Not Özetleyicisi & Sınav Tüyoları',
      'Öğretmen ve Profesör Onaylı Notlara Tam Erişim',
      'Mobil & Çevrimdışı Okuma Modu',
      'Yüklemelerde 2X Dijipuan Çarpanı'
    ],
    ctaText: '7 Gün Ücretsiz Dene'
  },
  {
    id: 'researcher',
    name: 'Araştırmacı & Doçent',
    badge: 'Akademik Kadro',
    priceMonthly: 149,
    priceYearly: 1390,
    description: 'Doktora, Doçentlik, Akademisyenler ve Telif Hak Sahibi Eğitmenler İçin.',
    features: [
      'Pro Akademik Tüm Özellikleri',
      'Kendi Not ve Fasiküllerini Satışa Çıkarma (Telif Geliri)',
      'Akademik Doğrulanmış Rozet (Verified Educator Badge)',
      'Gelişmiş AI Plagiat & Telif Denetim Araçları',
      'Doktora & Doçentlik Sunum Şablonları'
    ],
    ctaText: 'Akademisyen Hesabına Geç'
  }
];

/* ==========================================================================
   ADMIN DASHBOARD MOCK DATA
   ========================================================================== */

const AVATARS = {
  m1: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  m2: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
  m3: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
  f1: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
  f2: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
};

const PREVIEWS = {
  p1: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=70',
  p2: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=400&q=70',
  p3: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=400&q=70',
  p4: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=400&q=70',
  p5: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=70',
};

// --- Content & Note Moderation Queue ---
export const MOCK_MODERATION_QUEUE: ModerationItem[] = [
  {
    id: 'mod-1',
    noteTitle: '11. Sınıf TYT/AYT Fizik - Vektörler & Bağıl Hareket Tam Föy',
    authorName: 'Deniz Kaya',
    authorAvatar: AVATARS.m3,
    courseCode: 'YKS FİZ',
    courseName: 'Fizik (Mekanik & Vektörler)',
    educationTier: 'lise',
    level: '11. Sınıf',
    examType: 'TYT / AYT',
    submittedAt: '2026-07-28T08:14:00',
    pageCount: 32,
    fileSizeBytes: 4900000,
    plagiarismScore: 6,
    aiGeneratedScore: 4,
    status: 'pending_ai',
    previewImage: PREVIEWS.p3,
    dijipuanPrice: 15,
    isVerifiedAuthor: false,
  },
  {
    id: 'mod-2',
    noteTitle: 'Veri Yapıları CENG 201 - AVL & Red-Black Trees Vize Özeti',
    authorName: 'Ege Kaan Şahin',
    authorAvatar: AVATARS.m2,
    courseCode: 'CENG 201',
    courseName: 'Veri Yapıları ve Algoritma Analizi',
    educationTier: 'lisans',
    level: 'Lisans 2. Sınıf',
    examType: 'Vize',
    submittedAt: '2026-07-28T07:02:00',
    pageCount: 38,
    fileSizeBytes: 4200000,
    plagiarismScore: 71,
    aiGeneratedScore: 22,
    status: 'flagged',
    flagReason: 'Yüksek benzerlik: "GeeksForGeeks" ve önceki bir yükleme ile %71 örtüşme.',
    previewImage: PREVIEWS.p1,
    dijipuanPrice: 0,
    isVerifiedAuthor: true,
  },
  {
    id: 'mod-3',
    noteTitle: '8. Sınıf LGS Matematik - Çarpanlar & EBOB-EKOK Yeni Nesil Set',
    authorName: 'Caner Şahin',
    authorAvatar: AVATARS.m2,
    courseCode: 'LGS MAT',
    courseName: '8. Sınıf LGS Matematik',
    educationTier: 'ortaokul',
    level: '8. Sınıf (LGS)',
    examType: 'LGS Denemesi',
    submittedAt: '2026-07-27T19:40:00',
    pageCount: 40,
    fileSizeBytes: 5800000,
    plagiarismScore: 12,
    aiGeneratedScore: 9,
    status: 'pending_ai',
    previewImage: PREVIEWS.p2,
    dijipuanPrice: 10,
    isVerifiedAuthor: false,
  },
  {
    id: 'mod-4',
    noteTitle: 'Transformer Mimarileri Doktora Tez Özeti & Doçentlik Sunumu',
    authorName: 'Dr. Arda Yılmaz',
    authorAvatar: AVATARS.m3,
    courseCode: 'AI DOKTORA',
    courseName: 'İleri Derin Öğrenme Araştırmaları',
    educationTier: 'akademik',
    level: 'Doktora',
    examType: 'Tez Özeti',
    submittedAt: '2026-07-27T14:22:00',
    pageCount: 56,
    fileSizeBytes: 14200000,
    plagiarismScore: 3,
    aiGeneratedScore: 88,
    status: 'flagged',
    flagReason: 'AI üretim şüphesi: metnin %88\'i yapay zekâ ile üretilmiş olabilir.',
    previewImage: PREVIEWS.p5,
    dijipuanPrice: 25,
    isVerifiedAuthor: true,
  },
  {
    id: 'mod-5',
    noteTitle: '1. Sınıf İlkokuma Yazma - ANETİL Ses Grubu Çizgi Çalışmaları',
    authorName: 'Elif Öğretmen',
    authorAvatar: AVATARS.f1,
    courseCode: 'OKUMA 101',
    courseName: '1. Sınıf Okuma Yazma Etkinlikleri',
    educationTier: 'ilkokul',
    level: '1. Sınıf',
    examType: 'Okul Sınavı',
    submittedAt: '2026-07-27T11:05:00',
    pageCount: 24,
    fileSizeBytes: 3200000,
    plagiarismScore: 2,
    aiGeneratedScore: 1,
    status: 'approved',
    previewImage: PREVIEWS.p4,
    dijipuanPrice: 0,
    isVerifiedAuthor: true,
  },
  {
    id: 'mod-6',
    noteTitle: 'İşletim Sistemleri CENG 302 - Process Scheduling Notları',
    authorName: 'Mert Aydın',
    authorAvatar: AVATARS.m1,
    courseCode: 'CENG 302',
    courseName: 'İşletim Sistemleri',
    educationTier: 'lisans',
    level: 'Lisans 3. Sınıf',
    examType: 'Final',
    submittedAt: '2026-07-26T22:18:00',
    pageCount: 27,
    fileSizeBytes: 3600000,
    plagiarismScore: 34,
    aiGeneratedScore: 15,
    status: 'pending_ai',
    previewImage: PREVIEWS.p1,
    dijipuanPrice: 5,
    isVerifiedAuthor: false,
  },
  {
    id: 'mod-7',
    noteTitle: 'Anatomi Dönem 1 - Üst Ekstremite Kemikleri El Yazısı Notları',
    authorName: 'Ayşe Demir',
    authorAvatar: AVATARS.f1,
    courseCode: 'MED 101',
    courseName: 'Anatomi I',
    educationTier: 'lisans',
    level: 'Lisans 1. Sınıf',
    examType: 'Vize',
    submittedAt: '2026-07-26T16:44:00',
    pageCount: 45,
    fileSizeBytes: 8100000,
    plagiarismScore: 8,
    aiGeneratedScore: 3,
    status: 'rejected',
    flagReason: 'Reddedildi: Sayfaların bir kısmı okunaksız / düşük çözünürlüklü tarama.',
    previewImage: PREVIEWS.p2,
    dijipuanPrice: 8,
    isVerifiedAuthor: false,
  },
  {
    id: 'mod-8',
    noteTitle: 'YKS AYT Kimya - Organik Kimya Reaksiyon Haritaları',
    authorName: 'Selin Yıldız',
    authorAvatar: AVATARS.f2,
    courseCode: 'YKS KİM',
    courseName: 'Kimya (Organik)',
    educationTier: 'lise',
    level: '12. Sınıf (TYT/AYT)',
    examType: 'TYT / AYT',
    submittedAt: '2026-07-28T09:01:00',
    pageCount: 29,
    fileSizeBytes: 5200000,
    plagiarismScore: 18,
    aiGeneratedScore: 11,
    status: 'pending_ai',
    previewImage: PREVIEWS.p3,
    dijipuanPrice: 12,
    isVerifiedAuthor: false,
  },
];

// --- User & Subscription Management ---
export const MOCK_ADMIN_USERS: AdminUserRecord[] = [
  {
    id: 'u-1001', name: 'Ege Kaan Şahin', email: 'ege.sahin@itu.edu.tr', avatar: AVATARS.m2,
    university: 'İstanbul Teknik Üniversitesi', department: 'Bilgisayar Mühendisliği',
    role: 'PRO_STUDENT', status: 'active', dijipuanBalance: 4850, uploads: 48, downloads: 320,
    joinedAt: '2024-09-12', lastActive: '2 dk önce', isVerifiedEducator: false, reputationScore: 998,
  },
  {
    id: 'u-1002', name: 'Ayşe Demir', email: 'ayse.demir@ogr.hacettepe.edu.tr', avatar: AVATARS.f1,
    university: 'Hacettepe Üniversitesi', department: 'Tıp (Genel Tıp)',
    role: 'FREE_STUDENT', status: 'active', dijipuanBalance: 210, uploads: 3, downloads: 4,
    joinedAt: '2026-02-01', lastActive: '1 saat önce', isVerifiedEducator: false, reputationScore: 120,
  },
  {
    id: 'u-1003', name: 'Dr. Arda Yılmaz', email: 'arda.yilmaz@odtu.edu.tr', avatar: AVATARS.m3,
    university: 'Orta Doğu Teknik Üniversitesi', department: 'Bilgisayar Mühendisliği',
    role: 'RESEARCHER_DOCENT', status: 'active', dijipuanBalance: 8920, uploads: 67, downloads: 340,
    joinedAt: '2023-03-18', lastActive: 'Dün', isVerifiedEducator: true, reputationScore: 975,
  },
  {
    id: 'u-1004', name: 'Zeynep Öğretmen', email: 'zeynep.ogretmen@meb.gov.tr', avatar: AVATARS.f2,
    university: 'Milli Eğitim Bakanlığı', department: 'İlköğretim',
    role: 'RESEARCHER_DOCENT', status: 'active', dijipuanBalance: 6120, uploads: 120, downloads: 90,
    joinedAt: '2023-11-05', lastActive: '3 saat önce', isVerifiedEducator: true, reputationScore: 940,
  },
  {
    id: 'u-1005', name: 'Caner Şahin', email: 'caner.sahin@gmail.com', avatar: AVATARS.m2,
    university: 'Özel Bahçeşehir Koleji', department: '8. Sınıf (LGS)',
    role: 'PRO_STUDENT', status: 'active', dijipuanBalance: 1320, uploads: 22, downloads: 210,
    joinedAt: '2025-06-22', lastActive: '5 dk önce', isVerifiedEducator: false, reputationScore: 610,
  },
  {
    id: 'u-1006', name: 'Mert Aydın', email: 'mert.aydin@std.yildiz.edu.tr', avatar: AVATARS.m1,
    university: 'Yıldız Teknik Üniversitesi', department: 'Bilgisayar Mühendisliği',
    role: 'FREE_STUDENT', status: 'suspended', dijipuanBalance: 40, uploads: 6, downloads: 5,
    joinedAt: '2025-10-30', lastActive: '4 gün önce', isVerifiedEducator: false, reputationScore: 85,
  },
  {
    id: 'u-1007', name: 'Selin Yıldız', email: 'selin.yildiz@gmail.com', avatar: AVATARS.f2,
    university: 'Özel Ted Koleji', department: '12. Sınıf (TYT/AYT)',
    role: 'PRO_STUDENT', status: 'active', dijipuanBalance: 890, uploads: 14, downloads: 180,
    joinedAt: '2025-09-01', lastActive: '30 dk önce', isVerifiedEducator: false, reputationScore: 430,
  },
  {
    id: 'u-1008', name: 'Prof. Dr. Selin Korkmaz', email: 'selin.korkmaz@bilkent.edu.tr', avatar: AVATARS.f2,
    university: 'Bilkent Üniversitesi', department: 'Bilgisayar Mühendisliği',
    role: 'RESEARCHER_DOCENT', status: 'pending', dijipuanBalance: 0, uploads: 0, downloads: 12,
    joinedAt: '2026-07-25', lastActive: '2 gün önce', isVerifiedEducator: false, reputationScore: 0,
  },
  {
    id: 'u-1009', name: 'Can Yılmaz', email: 'can.yilmaz@itu.edu.tr', avatar: AVATARS.m1,
    university: 'İstanbul Teknik Üniversitesi', department: 'Bilgisayar Mühendisliği',
    role: 'PRO_STUDENT', status: 'active', dijipuanBalance: 1450, uploads: 14, downloads: 82,
    joinedAt: '2024-10-15', lastActive: 'Şimdi', isVerifiedEducator: false, reputationScore: 480,
  },
  {
    id: 'u-1010', name: 'Elif Öğretmen', email: 'elif.ogretmen@meb.gov.tr', avatar: AVATARS.f1,
    university: 'Milli Eğitim Bakanlığı', department: 'İlköğretim 1. Sınıf',
    role: 'RESEARCHER_DOCENT', status: 'active', dijipuanBalance: 3400, uploads: 58, downloads: 45,
    joinedAt: '2024-01-20', lastActive: '1 gün önce', isVerifiedEducator: true, reputationScore: 880,
  },
];

// --- Academic / Educator Verification Requests ---
export const MOCK_VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: 'ver-1',
    applicantName: 'Prof. Dr. Selin Korkmaz',
    applicantAvatar: AVATARS.f2,
    requestedTitle: 'Prof. Dr.',
    university: 'Bilkent Üniversitesi',
    department: 'Bilgisayar Mühendisliği',
    email: 'selin.korkmaz@bilkent.edu.tr',
    orcidId: '0000-0002-1825-0097',
    publicationCount: 84,
    hIndex: 31,
    submittedAt: '2026-07-25T10:12:00',
    status: 'pending',
    documents: [
      { label: 'Akademik Kimlik Kartı (Bilkent)', kind: 'Akademik Kimlik', verified: true },
      { label: 'ORCID Profili & Yayın Listesi', kind: 'ORCID', verified: true },
      { label: 'YÖK Doçentlik Belgesi', kind: 'Üniversite Belgesi', verified: false },
    ],
  },
  {
    id: 'ver-2',
    applicantName: 'Doç. Dr. Kaan Erdoğan',
    applicantAvatar: AVATARS.m1,
    requestedTitle: 'Doç. Dr.',
    university: 'Orta Doğu Teknik Üniversitesi',
    department: 'Elektrik-Elektronik Mühendisliği',
    email: 'kaan.erdogan@odtu.edu.tr',
    orcidId: '0000-0001-5109-3700',
    publicationCount: 47,
    hIndex: 19,
    submittedAt: '2026-07-24T15:33:00',
    status: 'under_review',
    documents: [
      { label: 'Akademik Kimlik Kartı (ODTÜ)', kind: 'Akademik Kimlik', verified: true },
      { label: 'ORCID Profili', kind: 'ORCID', verified: true },
      { label: 'Doçentlik Diploması', kind: 'Diploma', verified: true },
    ],
    note: 'Belgeler doğrulandı, ikinci imza bekleniyor.',
  },
  {
    id: 'ver-3',
    applicantName: 'Uzman Öğretmen Fatma Aksoy',
    applicantAvatar: AVATARS.f1,
    requestedTitle: 'Uzman Öğretmen',
    university: 'Milli Eğitim Bakanlığı',
    department: 'Ortaokul Matematik',
    email: 'fatma.aksoy@meb.gov.tr',
    orcidId: '—',
    publicationCount: 0,
    hIndex: 0,
    submittedAt: '2026-07-23T09:20:00',
    status: 'pending',
    documents: [
      { label: 'MEBBİS Uzman Öğretmenlik Belgesi', kind: 'Üniversite Belgesi', verified: true },
      { label: 'Kurum Kimlik Kartı', kind: 'Akademik Kimlik', verified: false },
    ],
  },
  {
    id: 'ver-4',
    applicantName: 'Dr. Öğr. Üyesi Baran Çelik',
    applicantAvatar: AVATARS.m2,
    requestedTitle: 'Dr. Öğr. Üyesi',
    university: 'Boğaziçi Üniversitesi',
    department: 'Moleküler Biyoloji ve Genetik',
    email: 'baran.celik@bogazici.edu.tr',
    orcidId: '0000-0003-4820-1123',
    publicationCount: 23,
    hIndex: 11,
    submittedAt: '2026-07-20T13:05:00',
    status: 'approved',
    documents: [
      { label: 'Akademik Kimlik Kartı', kind: 'Akademik Kimlik', verified: true },
      { label: 'ORCID Profili', kind: 'ORCID', verified: true },
      { label: 'Doktora Diploması', kind: 'Diploma', verified: true },
    ],
  },
  {
    id: 'ver-5',
    applicantName: 'Arş. Gör. Ceren Toprak',
    applicantAvatar: AVATARS.f2,
    requestedTitle: 'Arş. Gör.',
    university: 'Yıldız Teknik Üniversitesi',
    department: 'Makine Mühendisliği',
    email: 'ceren.toprak@yildiz.edu.tr',
    orcidId: '0000-0002-9981-4432',
    publicationCount: 5,
    hIndex: 3,
    submittedAt: '2026-07-19T17:48:00',
    status: 'rejected',
    documents: [
      { label: 'Kurum Kimlik Kartı', kind: 'Akademik Kimlik', verified: false },
      { label: 'ORCID Profili', kind: 'ORCID', verified: true },
    ],
    note: 'Reddedildi: Kimlik belgesi süresi dolmuş, güncel belge talep edildi.',
  },
];

// --- Telif & Copyright Claims / DMCA ---
export const MOCK_COPYRIGHT_CLAIMS: CopyrightClaim[] = [
  {
    id: 'dmca-1',
    noteId: 'note-101',
    noteTitle: 'Veri Yapıları CENG 201 - AVL & Red-Black Trees Vize Özeti',
    uploaderName: 'Ege Kaan Şahin',
    uploaderAvatar: AVATARS.m2,
    claimantName: 'Prof. Dr. Ahmet Yılmaz',
    claimantOrg: 'İstanbul Teknik Üniversitesi',
    claimType: 'Telif İhlali',
    reason: 'Notlar birebir benim ders slaytlarımdan izinsiz kopyalanmış. Şekiller ve örnekler bana ait.',
    reportedAt: '2026-07-27T12:30:00',
    status: 'open',
    severity: 'high',
    educationTier: 'lisans',
  },
  {
    id: 'dmca-2',
    noteId: 'note-mid-101',
    noteTitle: '8. Sınıf LGS Matematik Yeni Nesil Soru Bankası',
    uploaderName: 'Caner Şahin',
    uploaderAvatar: AVATARS.m2,
    claimantName: 'Yayınevi Hukuk Departmanı',
    claimantOrg: 'Aydın Yayıncılık A.Ş.',
    claimType: 'İzinsiz Ticari Kullanım',
    reason: 'Sorular telifli soru bankamızdan alınmış ve satışa sunulmuş (10 Dijipuan).',
    reportedAt: '2026-07-26T09:15:00',
    status: 'investigating',
    severity: 'high',
    educationTier: 'ortaokul',
  },
  {
    id: 'dmca-3',
    noteId: 'note-adv-101',
    noteTitle: 'Transformer Mimarileri Doktora Tez Özeti',
    uploaderName: 'Dr. Arda Yılmaz',
    uploaderAvatar: AVATARS.m3,
    claimantName: 'Anonim Kullanıcı',
    claimantOrg: '—',
    claimType: 'İntihal',
    reason: 'Metnin bir bölümü bir arXiv makalesinden atıfsız alıntılanmış görünüyor.',
    reportedAt: '2026-07-25T18:40:00',
    status: 'open',
    severity: 'medium',
    educationTier: 'akademik',
  },
  {
    id: 'dmca-4',
    noteId: 'note-high-101',
    noteTitle: '11. Sınıf TYT/AYT Fizik Vektörler Föyü',
    uploaderName: 'Deniz Kaya',
    uploaderAvatar: AVATARS.m3,
    claimantName: 'Murat Şen',
    claimantOrg: 'Bireysel Eğitmen',
    claimType: 'Kişisel Veri',
    reason: 'PDF içinde başka bir öğrencinin adı-numarası görünüyor, kaldırılmasını talep ediyorum.',
    reportedAt: '2026-07-24T14:02:00',
    status: 'dismissed',
    severity: 'low',
    educationTier: 'lise',
  },
  {
    id: 'dmca-5',
    noteId: 'note-elem-101',
    noteTitle: '1. Sınıf İlkokuma Yazma Çizgi Çalışmaları Fasikülü',
    uploaderName: 'Elif Öğretmen',
    uploaderAvatar: AVATARS.f1,
    claimantName: 'Görsel Tasarım Stüdyosu',
    claimantOrg: 'MiniÇizgi Tasarım',
    claimType: 'Telif İhlali',
    reason: 'Kullanılan karakter illüstrasyonları lisanslı görsel kütüphanemize ait.',
    reportedAt: '2026-07-22T11:50:00',
    status: 'taken_down',
    severity: 'medium',
    educationTier: 'ilkokul',
  },
];

// --- Monetization & Payout Approvals ---
export const MOCK_PAYOUT_REQUESTS: PayoutRequest[] = [
  {
    id: 'pay-1',
    userName: 'Dr. Arda Yılmaz',
    userAvatar: AVATARS.m3,
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    amountTRY: 2840,
    dijipuanRedeemed: 28400,
    method: 'IBAN',
    accountRef: 'TR** **** **** **** **12 34',
    salesCount: 142,
    requestedAt: '2026-07-27T10:00:00',
    status: 'pending',
  },
  {
    id: 'pay-2',
    userName: 'Zeynep Öğretmen',
    userAvatar: AVATARS.f2,
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    amountTRY: 1620,
    dijipuanRedeemed: 16200,
    method: 'iyzico',
    accountRef: 'iyzico • zeynep***@meb.gov.tr',
    salesCount: 89,
    requestedAt: '2026-07-26T16:20:00',
    status: 'pending',
  },
  {
    id: 'pay-3',
    userName: 'Prof. Dr. Selin Korkmaz',
    userAvatar: AVATARS.f2,
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: false,
    amountTRY: 4100,
    dijipuanRedeemed: 41000,
    method: 'Stripe',
    accountRef: 'acct_1Qx***KorK',
    salesCount: 63,
    requestedAt: '2026-07-26T08:45:00',
    status: 'pending',
  },
  {
    id: 'pay-4',
    userName: 'Elif Öğretmen',
    userAvatar: AVATARS.f1,
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    amountTRY: 980,
    dijipuanRedeemed: 9800,
    method: 'IBAN',
    accountRef: 'TR** **** **** **** **88 21',
    salesCount: 44,
    requestedAt: '2026-07-24T12:10:00',
    status: 'approved',
  },
  {
    id: 'pay-5',
    userName: 'Dr. Öğr. Üyesi Baran Çelik',
    userAvatar: AVATARS.m2,
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: true,
    amountTRY: 1340,
    dijipuanRedeemed: 13400,
    method: 'IBAN',
    accountRef: 'TR** **** **** **** **05 77',
    salesCount: 51,
    requestedAt: '2026-07-21T09:30:00',
    status: 'paid',
  },
  {
    id: 'pay-6',
    userName: 'Kaan Erdoğan',
    userAvatar: AVATARS.m1,
    role: 'RESEARCHER_DOCENT',
    isVerifiedEducator: false,
    amountTRY: 620,
    dijipuanRedeemed: 6200,
    method: 'Stripe',
    accountRef: 'acct_1Rd***ErdG',
    salesCount: 18,
    requestedAt: '2026-07-20T15:00:00',
    status: 'rejected',
  },
];

// --- Analytics ---
export const MOCK_TIER_UPLOAD_STATS: TierUploadStat[] = [
  { tier: 'ilkokul', label: 'İlkokul', count: 1240, barClass: 'bg-emerald-500' },
  { tier: 'ortaokul', label: 'Ortaokul & LGS', count: 3180, barClass: 'bg-cyan-500' },
  { tier: 'lise', label: 'Lise & YKS', count: 5420, barClass: 'bg-indigo-500' },
  { tier: 'lisans', label: 'Lisans', count: 8760, barClass: 'bg-blue-500' },
  { tier: 'akademik', label: 'İleri Akademik', count: 2090, barClass: 'bg-purple-500' },
];

export const MOCK_DAILY_ACTIVE: DailyActiveStat[] = [
  { day: 'Pzt', users: 8200 },
  { day: 'Sal', users: 9100 },
  { day: 'Çar', users: 8700 },
  { day: 'Per', users: 10400 },
  { day: 'Cum', users: 11900 },
  { day: 'Cmt', users: 7600 },
  { day: 'Paz', users: 6800 },
];

export const MOCK_REVENUE_STATS: RevenueStat[] = [
  { month: 'Şub', revenueTRY: 184000, payoutsTRY: 62000 },
  { month: 'Mar', revenueTRY: 210500, payoutsTRY: 74500 },
  { month: 'Nis', revenueTRY: 238900, payoutsTRY: 81200 },
  { month: 'May', revenueTRY: 262400, payoutsTRY: 96800 },
  { month: 'Haz', revenueTRY: 291700, payoutsTRY: 108300 },
  { month: 'Tem', revenueTRY: 318600, payoutsTRY: 121900 },
];

export const MOCK_ADMIN_NOTIFICATIONS: AdminNotification[] = [
  { id: 'n-1', type: 'dmca', title: 'Yeni yüksek öncelikli telif talebi', detail: 'Prof. Dr. Ahmet Yılmaz — CENG 201 notu için telif ihlali bildirdi.', time: '5 dk önce', unread: true },
  { id: 'n-2', type: 'moderation', title: 'AI moderasyon uyarısı', detail: 'Bir Doktora tezinde %88 AI üretim şüphesi tespit edildi.', time: '18 dk önce', unread: true },
  { id: 'n-3', type: 'verification', title: 'Doçentlik doğrulama başvurusu', detail: 'Prof. Dr. Selin Korkmaz akademik rozet başvurusu yaptı.', time: '1 saat önce', unread: true },
  { id: 'n-4', type: 'payout', title: 'Ödeme talebi bekliyor', detail: 'Dr. Arda Yılmaz — 2.840 ₺ IBAN ödeme talebi onay bekliyor.', time: '3 saat önce', unread: false },
  { id: 'n-5', type: 'system', title: 'Sistem: OCR kuyruğu yoğun', detail: 'AI OCR işleme kuyruğunda 312 belge bekliyor.', time: 'Bugün 07:40', unread: false },
];

export const MOCK_ADMIN_OVERVIEW: AdminOverviewStats = {
  usersByRole: {
    FREE_STUDENT: 128450,
    PRO_STUDENT: 41280,
    RESEARCHER_DOCENT: 3610,
  },
  totalUsers: 173340,
  totalNotes: 20690,
  pendingModeration: 312,
  pendingVerifications: 24,
  openClaims: 9,
  pendingPayouts: 17,
  monthlyRevenueTRY: 318600,
  monthlyPayoutsTRY: 121900,
  dijipuanCirculating: 4820000,
};
